apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: frontend
          image: shivasaiprasad/chat-frontend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
